# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "plantinux"

BBFILE_PATTERN_plantinux = "^${LAYERDIR}/"

BBFILE_PRIORITY_plantinux = "20"

LAYERSERIES_COMPAT_plantinux = "scarthgap"